 create sequence hibernate_sequence start 1 increment 1;
 create table book_table (id int8 not null, create_date timestamp, status int4, update_date timestamp, author varchar(255), description text, title varchar(255), primary key (id));
 create table category_table (id int8 not null, create_date timestamp, status int4, update_date timestamp, title varchar(255), primary key (id));
 create table hadith_table (id int8 not null, create_date timestamp, status int4, update_date timestamp, description text, title varchar(255), book_id int8, category_id int8, primary key (id));
 create table login_table (id int8 not null, create_date timestamp, status int4, update_date timestamp, credential varchar(255), password varchar(255), type int4, primary key (id));
 create table saves_table (id int8 not null, create_date timestamp, status int4, update_date timestamp, hadyth_id int8, user_id int8, primary key (id));
 create table setting_table (id int8 not null, create_date timestamp, status int4, update_date timestamp, count_of_notif int4 not null, is_notif_enabled boolean not null, last_sent_hadith_id int8, primary key (id));
 create table user_table (id int8 not null, create_date timestamp, status int4, update_date timestamp, password varchar(255), user_name varchar(255), login_entity_id int8, setting_entity_id int8, primary key (id));
 create table user_entity_roles (user_entity_id int8 not null, roles int4);
 alter table category_table add constraint UK_4q9528onn187nd1odde3celaa unique (title);
 alter table hadith_table add constraint FKfpghlafoaf9lwfmy869q9fnvt foreign key (book_id) references book_table;
 alter table hadith_table add constraint FKn8j1ubrvgmqnmf8wghpi4hiyv foreign key (category_id) references category_table;
 alter table saves_table add constraint FKhd7y1oiytyai16t43e3ifcpba foreign key (hadyth_id) references hadith_table;
 alter table saves_table add constraint FKrlfnomx3qftvbg8bje7ef7a11 foreign key (user_id) references user_table;
 alter table setting_table add constraint FK342exrcij858wiuabh3iq3dto foreign key (last_sent_hadith_id) references hadith_table;
 alter table user_table add constraint FKf8rl5l6v4wh1gbrn6prr0592u foreign key (login_entity_id) references login_table;
 alter table user_table add constraint FKr5eg5jjny1m4squ3cwm97c9v7 foreign key (setting_entity_id) references setting_table;
 alter table user_entity_roles add constraint FKou4fmyn06n8avymtilmweq2i6 foreign key (user_entity_id) references user_table;