-- insert into category_table(create_date, status, update_date, title)
-- VALUES (current_date, 0, current_date, 'Category 1');
-- insert into category_table(create_date, status, update_date, title)
-- VALUES (current_date, 0, current_date, 'Category 2');
--
-- insert into book_table(create_date, status, update_date, author, description, title)
-- VALUES (current_date, 0, current_date, 'Author 1', 'Description .....', 'Book 1');
-- insert into book_table(create_date, status, update_date, author, description, title)
-- VALUES (current_date, 0, current_date, 'Author 2', 'Description .....', 'Book 2');
--
-- insert into hadith_table(create_date, status, update_date, description, title, category_id, book_id)
-- VALUES (current_date, 0, current_date, 'Description .....', 'Hadith 1',
--         (select id from category_table where hadith_table.title = 'Category 1'),
--         (select id from book_table where title = 'Book 1'));
-- insert into hadith_table(create_date, status, update_date, description, title, category_id, book_id)
-- VALUES (current_date, 0, current_date, 'Description .....', 'Hadith 2',
--         (select id from category_table where hadith_table.title = 'Category 1'),
--         (select id from book_table where title = 'Book 1'));
-- insert into hadith_table(create_date, status, update_date, description, title, category_id, book_id)
-- VALUES (current_date, 0, current_date, 'Description .....', 'Hadith 3',
--         (select id from category_table where hadith_table.title = 'Category 2'),
--         (select id from book_table where title = 'Book 2'));
-- insert into hadith_table(create_date, status, update_date, description, title, category_id, book_id)
-- VALUES (current_date, 0, current_date, 'Description .....', 'Hadith 4',
--         (select id from category_table where hadith_table.title = 'Category 2'),
--         (select id from book_table where title = 'Book 2'));
--
-- insert into login_table (create_date, status, update_date, credential, password, type)
-- values (current_date, 0, current_date, '10.123.323.23.123', '', 0);
-- insert into login_table (create_date, status, update_date, credential, password, type)
-- values (current_date, 0, current_date, '0550985580', '123456', 1);
--
-- insert into setting_table(create_date, status, update_date, count_of_notif, is_notif_enabled, last_sent_hadith_id)
-- VALUES (current_date, 0, current_date, 1, true, (select id from hadith_table where title = 'Hadith 1'));
-- insert into setting_table(create_date, status, update_date, count_of_notif, is_notif_enabled, last_sent_hadith_id)
-- VALUES (current_date, 0, current_date, 3, true, (select id from hadith_table where title = 'Hadith 2'));
--
-- insert into user_table (create_date, status, update_date, user_name, login_entity_id, setting_entity_id)
-- values (current_date, 0, current_date, 'User 1',
--         (select id from login_table where credential = '10.123.323.23.123'),
--         (select id from hadith.public.setting_table where count_of_notif = 1));
-- insert into user_table (create_date, status, update_date, user_name, login_entity_id, setting_entity_id)
-- values (current_date, 0, current_date, 'User 2',
--         (select id from login_table where credential = '0550985580'),
--         (select id from hadith.public.setting_table where count_of_notif = 2));
--
-- insert into saves_table (create_date, status, update_date, hadyth_id, user_id)
-- values (current_date, 0, current_date,
--         (select id from hadith_table where title = 'Hadith 1'),
--         (select id from user_table where user_name = 'User 1'));
-- insert into saves_table (create_date, status, update_date, hadyth_id, user_id)
-- values (current_date, 0, current_date,
--         (select id from hadith_table where title = 'Hadith 2'),
--         (select id from user_table where user_name = 'User 1'));
-- insert into saves_table (create_date, status, update_date, hadyth_id, user_id)
-- values (current_date, 0, current_date,
--         (select id from hadith_table where title = 'Hadith 3'),
--         (select id from user_table where user_name = 'User 1'));
--
